### ISSUE TITLE
can we use it on heroku?

### ISSUE THREAD

**Issue by tomahocbc** [ContentAutomation/YouTubeUploader#9]

**Comment by MorMundHS-MA** [comment]
I don't have experience with Heroku, so I can't give you a definitive answer. The critical thing is running the docker image containing the browser. For our AWS instance we used a 1 GB instance I think, because smaller instances ran out of memory running the image. If Heroku provides runtimes that large and allows running the browser image, I don't see why it shouldn't work.

However you should also be aware that currently YouTube is blocking uploads from automated browser (see this issue for more info #8).

**Comment by tomahocbc** [comment]
> I don't have experience with Heroku, so I can't give you a definitive answer. The critical thing is running the docker image containing the browser. For our AWS instance we used a 1 GB instance I think, because smaller instances ran out of memory running the image. If Heroku provides runtimes that large and allows running the browser image, I don't see why it shouldn't work.
> 
> However you should also be aware that currently YouTube is blocking uploads from automated browser (see this issue for more info #8).

thanks, bro for answering my question
